// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwBl7y8Wd0AaXqRVfFMcRueaY4jH7DAUo',
    appId: '1:371587610057:android:31d91e0799a2f277976418',
    messagingSenderId: '371587610057',
    projectId: 'todo-app-33898',
    storageBucket: 'todo-app-33898.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB448PiJwf5FIfr0ELy79v1WH4ny9WFHDc',
    appId: '1:371587610057:ios:2df5eb7c3683b03d976418',
    messagingSenderId: '371587610057',
    projectId: 'todo-app-33898',
    storageBucket: 'todo-app-33898.firebasestorage.app',
    androidClientId: '371587610057-0a461opvobmh2gjcmrpbmm25mffdvh8v.apps.googleusercontent.com',
    iosClientId: '371587610057-t2hj8tgosns08rs425s978ou982okput.apps.googleusercontent.com',
    iosBundleId: 'com.example.newtodoapp',
  );
}